### PR TITLE
Add pull request templates

### PR DESCRIPTION
**Pull request by nadavsu**
# Description
Pull request templates make PR descriptions easier to read and understand. After adding pull request templates to our repository, project contributors will automatically see the template's contents in the pull request body.
The template in this PR description is the template that we'll be using.

## Screenshots
(Here you should attach screenshots related to this PR, if there are any.)

## Manual Tests
(Here you should list a list of **manual** tests you've done.)

## Additional Information
(Here you should list additional information about the PR, such as new technologies used, or whether the documentation needs to be updated)

More information about PR templates [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)

### Issues close by this PR
(Here you should list the issues this PR closes)

### PR Dependencies
(Here you should list the PRs which this PR depends on)

### CODE REVIEW

**Review by AmitAharoni — APPROVED** [review]
Those `.github` files are so easy to do and important.
I love it.

**Review by Micha546 — COMMENTED** [review]
Looking good
I do think that the PR Dependencies needs to be at the top, if someone misses this it's really bad

**Review by DanielMy777 — COMMENTED** [review]
Prettiest thing i've seen

**Review by simzacks — APPROVED** [review]

**Comment by OrAsaf** [comment]
Great that you're adding those and improving the overall GitHub repo.
LGTM

**Pull request merged**
