### PR TITLE
Fix #30 Adding pytest-django to the project

### LINKED ISSUE #30: Add pytest to the project
Need to add `pytest` or `pytest-django` to the project -  includes ensuring that pytest is installed automatically when `vagrant up` is called

### PR DESCRIPTION
**Pull request by Micha546**
Ran pipenv install --dev pytest-django,
so vagrant up will install pytest.
Created pytest.ini to let pytest know where the project is.

pytest installing guide I followed:
https://djangostars.com/blog/django-pytest-testing/

All changes were computer generated but the pytest.ini file

Fix #30

### CODE REVIEW

**Comment by Micha546** [comment]
fix #30

**Comment by Omeramsc** [comment]
Adding the "fix" header to a comment/title of the PR won't link it. 
please mention it in the main PR message

**Review by Omeramsc — APPROVED** [review]
LGTM

**Review by Omeramsc — APPROVED** [review]

**Comment by OrAsaf** [comment]
LGTM

**Pull request merged**
