### PR TITLE
Move seeker

### LINKED ISSUE #74: Move seeker model to the seeker app

### LINKED ISSUE #89: Create new migration files

### PR DESCRIPTION
**Pull request by Micha546**
This PR is depended on #90 !!!
PR #90 has to be merged before this PR!

Moved Seeker, Added migration files...

**note:** before running `vagrant provision` / `migrate` make sure to delete db.sqlite3

Fix #89
Fix #74

### CODE REVIEW

**Review by DanielMy777 — COMMENTED** [review]
Considering you checked and that this works, it looks great.
Good job!

**Comment by tamirho** [comment]
> Considering you checked and that this works, it looks great.
> Good job!

As @DanielMy777 said..
LGTM

**Review by tamirho — APPROVED** [review]
> Considering you checked and that this works, it looks great.

As @DanielMy777 said..
LGTM

**Review by simzacks — CHANGES_REQUESTED** [review]
#90 must be merged before this, or you will delete the 0001_initial.py file

**Review by simzacks — APPROVED** [review]

**Comment by Micha546** [comment]
> #90 must be merged before this, or you will delete the 0001_initial.py file

Yes, I wrote that in the description as well, I'll update it so it will stand out more.

**Comment by OrAsaf** [comment]
@Micha546 I merged #90  and now we get some conflicts on this PR.
Resolve those and then we can verify.

**Comment by Micha546** [comment]
> @Micha546 I merged #90 and now we get some conflicts on this PR.
> Resolve those and then we can verify.

rebased and pushed again, now the commits are much cleaner

**Pull request merged**
