### PR TITLE
Adding a Vagrantfile to start a development VM

### PR DESCRIPTION
**Pull request by DanielMy777**
1) Adding a Vagrantfile to spin up a fedora-32 development machine.
2) Making changes in the '.gitignore' file to ignore internal
   files and data that Vagrant[1] creates.

[1]: https://www.vagrantup.com/

### CODE REVIEW

**Review by simzacks — APPROVED** [review]

**Comment by simzacks** [comment]
Before merging, please create an issue and link it to this PR, as specified in the slack discussion

**Comment by simzacks** [comment]
fixes #1

**Comment by simzacks** [comment]
fixes #1

**Comment by simzacks** [comment]
fixes #2

**Comment by 1Oreo** [comment]
fixes #2

**Pull request merged**
