### PR TITLE
Adding update forms for the user fields

### LINKED ISSUE #166: Add forms to change a user fields and password

### PR DESCRIPTION
**Pull request by Micha546**
# Description
Added UserUpdateForm and used the PasswordChangeForm from Django
to change the users password.
Added users url to the urls in roo_mo.urls.
Added html for the user update and for the password change
Added some tests to check that everything works

## Screenshots
updateuser

changepass

## Manual Tests
Changed the user fields and password through the forms

### Issues closed by this PR
Fix #166

### CODE REVIEW

**Comment by tamirho** [comment]
Graet!

**Review by DanielMy777 — COMMENTED** [review]
Great work!

**Comment by AmitAharoni** [comment]
Good job!

**Review by simzacks — APPROVED** [review]

**Review by nadavsu — APPROVED** [review]
LGTM

**Pull request merged**
