### PR TITLE
Add Account drop-down to navbar

### LINKED ISSUE #171: Alter the navbar to view Account links
- Need to add a drop-down list to the navbar to view all links related to the Account.

### PR DESCRIPTION
**Pull request by tamirho**
# Description
- Add a script tag to support `bootstrap js`.
- Add a `drop-down list` to the `navbar` to view all links related to the Account.

## Screenshots
Capture
--
Capture2

## Additional Information
In the future, we need to change the `href` property of the `<a>` tags to point to the right pages.

### Issues closed by this PR
Fix #171

### CODE REVIEW

**Review by OrAsaf — APPROVED** [review]

**Review by Micha546 — COMMENTED** [review]
🔥

**Comment by AmitAharoni** [comment]
🔥🔥🔥

**Review by DanielMy777 — COMMENTED** [review]
Lookin cool 🔥

**Review by Omeramsc — CHANGES_REQUESTED** [review]
LGTM, but separate the last part (`Change the navbar structure`) to a separate PR (as this PR title is specifically about the Account drop-down)

**Comment by OrAsaf** [comment]
This PR also has a conflict due to a merge so it needs to be sorted as well.

**Comment by tamirho** [comment]
@Omeramsc 
> LGTM, but separate the last part (Change the navbar structure) to a separate PR (as this PR title is specifically about the Account drop-down)

I will add another PR with the other changes... Now all the changes in this PR related to the drop-down functionality.

---

@1Oreo 
> This PR also has a conflict due to a merge so it needs to be sorted as well.

Done.

---

Please review it again.
**Notice:** It looks like I did a lot of changes in the file, but it's because I used a formatting option in vs code that restructures the file.

**Pull request merged**
