### PR TITLE
Adding apartments app

### LINKED ISSUE #66: Add apartments app to the project
- Create a new app called `apartments`

### PR DESCRIPTION
**Pull request by tamirho**
- Create the `apartments` app and register it in the `settings.py` file

fix #66

### CODE REVIEW

**Review by simzacks — APPROVED** [review]
LGTM

**Review by Micha546 — COMMENTED** [review]
Looks good!
🥇

**Review by DanielMy777 — COMMENTED** [review]
Looking good!

**Comment by Omeramsc** [comment]
There is too much stuff in this one PR, Please divide it.

**Review by Omeramsc — CHANGES_REQUESTED** [review]
There is too much stuff in this one PR, Please divide it.

**Comment by tamirho** [comment]
> There is too much stuff in this one PR, Please divide it.

Okay, I split it into two PRs.
In this PR I just added the apartment app and in #72 I moved the Apartment and City data models to this app.

**Review by simzacks — APPROVED** [review]

**Review by Omeramsc — APPROVED** [review]
LGTM

**Pull request merged**
