### PR TITLE
Adding 'status' field to the 'Connection' model 

### LINKED ISSUE #111: Add 'Pending' field to the connection model
The Connection model needs a field 'Pending', for owners to be able to approve connections before connecting.
Required outcome:
A functional 'pendin' field with automated tests.

### PR DESCRIPTION
**Pull request by DanielMy777**
1) Adding the status field as a custom choiceField.
2) Creating new methods for the Connection model, regarding the status field.
3) Creating tests for the field and methods.
[THIS PR SHOULD BE MERGED AFTER #92 AND WILL NEED A SMALL REBASE - DONE]
fix #111 
NOTE: New migration file was left untouched.

### CODE REVIEW

**Review by Micha546 — COMMENTED** [review]
🔥 
Personally I would add the dependency in the PR title to avoid errors 🥇

**Review by AmitAharoni — APPROVED** [review]
Awesome Daniel

**Review by simzacks — APPROVED** [review]

**Review by Omeramsc — APPROVED** [review]
LGTM

**Comment by OrAsaf** [comment]
@DanielMy777 we have merged #92. Please rebase and make sure the only necessary files are included in the PRs changed files.

**Comment by DanielMy777** [comment]
> @DanielMy777 we have merged #92. Please rebase and make sure the only necessary files are included in the PRs changed files.

@1Oreo @simzacks @Omeramsc 
I've rebased and made sure it still works properly, please continue with the merging process =]

**Pull request merged**
