### PR TITLE
Adding a script to generate migrations upon provisioning

### LINKED ISSUE #45: Update Flake8
Currently the max line length in the Flake8 is 120.
There are very long lines in the migrations files.

We will update Flake8 tool max line length 260.

### LINKED ISSUE #48: Remove migrations and add the migration files to .gitignore
Migration files can cause a lot of merging issues. The migration files should be added to the .gitignore file. 
Also, we should add the `makemigrations` instruction to bootstrap.sh, so that every time vagrant is provisioned the migration files will be generated.

### PR DESCRIPTION
**Pull request by nadavsu**
All files in `users/migrations` have been added to `.gitignore`, except for the test data file.
A script to generate migrations has been added to `bootstrap.sh`

**How it works:** after pulling from upstream, run `vagrant provision` in order to update/generate the migrations on origin. This will create a unifrom migration directory for every contributor working on this project.
The test data file (`*_test_data.py`) should be pushed if updated, as it is not generated automatically by Django.

Fixes #48
Fixes #45 because migration files will not be pushed anymore

### CODE REVIEW

**Comment by nadavsu** [comment]
Also resolves #45, because migration files are ignored.

**Comment by AmitAharoni** [comment]
Good job Nadav!
This PR also fixes #45. 
If `.gitignore` includes the migrations autogenreated files, no need to update Flake8.

**Review by Omeramsc — APPROVED** [review]
LGTM
@simzacks WDYT?

**Comment by OrAsaf** [comment]
LGTM (I assume it was tested and works properly).
I would also like to see Sim's take on this PR since he had an interesting debate on the matter of the the migration files.

**Comment by nadavsu** [comment]
Actually, @DanielMy777 said that there's a problem with this PR at #55 - it won't work with test data files.
I think we should talk about it before we approve this PR.

**Comment by DanielMy777** [comment]
> Actually, @DanielMy777 said that there's a problem with this PR at #55 - it won't work with test data files.
> I think we should talk about it before we approve this PR.

Agreed. IMO migration files should be kept anyway.
Since changes to data models were intense in the past couple of weeks, we had some troubles merging those migration files. But I think that from now on they wont cause an uncontrollable issue like they used to. (we wont be touching data models as much)

**Comment by simzacks** [comment]
It looks like I was mistaken about the migration files. The test data and preloaded data are going to be dependent on specific migration files. That means that if you store this file, you probably have to store all the other ones as well.
Unless you could mark the test data as being dependent only on the 001_initial.
However, I haven't tried this and would require some playing around.

It seems that all the other teams (and previous teams) are storing the migration files.

**Comment by nadavsu** [comment]
I'm closing this PR for now, looks like we found another way to do it.

**Pull request closed without merging**
