### PR TITLE
Add Meaningful and accurate test data

### LINKED ISSUE #142: Add Meaningful and accurate test data
We would like to  have
- Meaningful and accurate data.
- Add more fields to the data.
- Data that matches the search mechanics and the matching algorithm.
- Test data user based on each team member.

We will add users, seekers, apartments and contacts to the DB.

**Is your feature request related to a problem? Please describe.**
related to #138

### PR DESCRIPTION
**Pull request by AmitAharoni**
# Description
Add users, seeker, apartments and contacts to the DB.
-Meaningful and accurate data.
-Add more fields to the data.
-Data that matches the search mechanics and the matching algorithm.
-Test data user based on each team member.

## Screenshots
image

### Issues close by this PR
fix: #142 

### PR Dependencies
This PR dependent on #139,  #141 please don't merge before them.
needs rebase.

### CODE REVIEW

**Comment by tamirho** [comment]
I think that it's a great idea to add accurate test data, Also I think that we need to add more (a lot more) users and especially apartments to demonstrate a good search and filters. 
Can you add some? 
Maybe a good idea is to generate a list of 'first names' and 'last names' and use random to mix between them and to fill all the other fields. What do you think?

**Comment by AmitAharoni** [comment]
@tamirho 
I like the idea!
I believe we will add that when the search will be ready.

**Comment by tamirho** [comment]
LGTM

**Review by simzacks — APPROVED** [review]
This has to be rebased and merged after #141

**Comment by OrAsaf** [comment]
@AmitAharoni please rebase this PR I have merged #141.

**Comment by AmitAharoni** [comment]
@1Oreo 
Done

**Comment by DanielMy777** [comment]
:fire:
Looks good!

**Review by OrAsaf — APPROVED** [review]

**Pull request merged**
