### PR TITLE
Adding Django Crispy Forms to the repository

### LINKED ISSUE #95: Add crispy forms to the project
Crispy forms is a Django tool that is capable to design forms easily,
A good addition to the project.

### PR DESCRIPTION
**Pull request by DanielMy777**
1) Installing 'django-crispy-forms'[1] in the machine.
2) Registering crispy forms in the installed apps of the project.
3) Changing the login redirect page to be the home page.
[1]: https://django-crispy-forms.readthedocs.io/en/latest/
fix #95

### CODE REVIEW

**Comment by tamirho** [comment]
Looking good!

**Review by OrAsaf — APPROVED** [review]

**Review by Micha546 — COMMENTED** [review]
🔥

**Comment by nadavsu** [comment]
Lookin' crispy.

**Review by Omeramsc — APPROVED** [review]
LGTM

**Pull request merged**
