### PR TITLE
Adding Django development environment to the VM

### PR DESCRIPTION
**Pull request by Micha546**
Now after manually installing Pipenv and Django we can run
pipenv run python manage.py runserver 0.0.0.0:8000 (inside the VM)
and get to the Django development environment at 127.0.0.1:8000

HTTP access was already provided in the vagrantfile by Daniel

**note** Project folder is named roo_me and not roo.me
         this is because django doesn't allow . in project names

**note** ALL the files were automatically created

### CODE REVIEW

**Comment by OrAsaf** [comment]
@Micha546 please reference an issue this PR fixes so the two will be linked.

**Comment by Micha546** [comment]
fixes #3

**Review by simzacks — APPROVED** [review]
lgtm

**Review by DanielMy777 — COMMENTED** [review]
Looking good
:+1:

**Review by nadavsu — APPROVED** [review]
Nice

**Review by Omeramsc — APPROVED** [review]
LGTM

**Pull request merged**
