### PR TITLE
Adding test data file

### LINKED ISSUE #50: Add test data to users app
Expected outcome:
- Test data for hobby model
- Test data for city model
- Test data for user model
- Test data for apartment model
- Test data for seeker model

### PR DESCRIPTION
**Pull request by DanielMy777**
Adding test data for:
User, Seeker, Apartment, Hobby & City models.
_**NOTE**_
After discussion, we will leave migration files in the repo. Therefore, '0004' migration was auto generated containing the migrations we missed in the last couple of PR's (seeker model & user model update).
fix #50

### CODE REVIEW

**Comment by nadavsu** [comment]
Yep, there ~might be~ is an issue with this and #49.

**Comment by DanielMy777** [comment]
@simzacks @Omeramsc @1Oreo 
This PR is now ready for review :)

**Review by Micha546 — COMMENTED** [review]
Looking good 🔥

**Review by simzacks — APPROVED** [review]
LGTM

**Comment by OrAsaf** [comment]
LGTM

**Pull request merged**
