### PR TITLE
Add sidebar to base template

### LINKED ISSUE #104: Add sidebar to base template
All pages that inherit from the base template will include a sidebar, so making a sidebar block at the base template is the logical thing to do.

### PR DESCRIPTION
**Pull request by nadavsu**
Base template now includes a sidebar block, can be referenced via `{% block sidebar}` at every page that inherits the base template.

Also, added a logout button and fixed some links in navbar.

Resolves #104

### CODE REVIEW

**Review by AmitAharoni — APPROVED** [review]
Well done.

Don't forget to tag the mentors as reviewers.

**Review by Micha546 — COMMENTED** [review]
🔥

**Comment by tamirho** [comment]
Looks Good!

**Review by DanielMy777 — COMMENTED** [review]
🏆 Looks good!

**Review by simzacks — APPROVED** [review]

**Comment by OrAsaf** [comment]
LGTM

**Pull request merged**
