### PR TITLE
Adding is_seeker/owner properties to User model

### LINKED ISSUE #83: Add properties to check user type
- Add properties to `User` check if a user is a seeker or is an owner.

### PR DESCRIPTION
**Pull request by tamirho**
- Add is_seeker and is_owner properties to the 'User' model in order to
enable a quick way to check what is the type of user.
- Add test for these methods.

fix #83

### CODE REVIEW

**Review by simzacks — APPROVED** [review]

**Comment by OrAsaf** [comment]
@tamirho  this PR includes testing, please rebase it so purest will run as part of the PR.

**Review by DanielMy777 — COMMENTED** [review]
Looking cool

**Comment by tamirho** [comment]
> @tamirho this PR includes testing, please rebase it so purest will run as part of the PR.

@1Oreo 
We need to merge #85 before this PR.. since it resolves an import error.

**Comment by OrAsaf** [comment]
ack, I reviewed #85 and we will wait with the current PR. Make sure to track the progress on the other PR.

**Comment by tamirho** [comment]
@1Oreo 
I fixed the problem and there is no dependency on other PRs now.

**Review by OrAsaf — APPROVED** [review]

**Pull request merged**
