### PR TITLE
Fix save method in apartmentCreationForm

### LINKED ISSUE #152: Alter the save() function of the creation forms
**Describe the bug**
Right now were calling super().save() in the save method, which is saveing to the database because `commit=True` is the 
default option.
I think this is causing undefined behavior

**To Reproduce**
create a new user with the form
save

usually works fine, so I think this is undefined behavior

### PR DESCRIPTION
**Pull request by Micha546**
# Description
This PR is Depended on #147!!! - merged
Do not merge this PR before #147! - merged

bug fix in the save function of the apartmentCreationForm
adding tests for the save functions of apartmentCreationForm and seekerCreationForm

## Screenshots
image

## Manual Tests
Created an apartment user through the apartmentCreationForm

### Issues close by this PR
Fix #152 

### PR Dependencies
Depended on #147 - merged

### CODE REVIEW

**Review by DanielMy777 — COMMENTED** [review]
Looks good! 👍

**Review by nadavsu — APPROVED** [review]

**Review by simzacks — COMMENTED** [review]
Please rebase. I merged 147

**Comment by Micha546** [comment]
> Please rebase. I merged 147

Rebased 👍

**Comment by AmitAharoni** [comment]
LGTM

**Comment by tamirho** [comment]
LGTM

**Review by simzacks — APPROVED** [review]
I am getting a bit confused at previous functionality that I didn't catch earlier in already merged code.
In forms, the commit parameter has a default of False, but on the model, the commit parameter has a default of True.
That leads to a situation where sometimes you call .save() and it is a real save and sometimes you call .save() and it isn't a real save.
I'm going to approve this PR, as that is the functionality that is already included in the merged code, but I recommend keeping to a standard so that the default on functions like save are the same across the board.

**Comment by Micha546** [comment]
> I am getting a bit confused at previous functionality that I didn't catch earlier in already merged code.
> In forms, the commit parameter has a default of False, but on the model, the commit parameter has a default of True.
> That leads to a situation where sometimes you call .save() and it is a real save and sometimes you call .save() and it isn't a real save.
> I'm going to approve this PR, as that is the functionality that is already included in the merged code, but I recommend keeping to a standard so that the default on functions like save are the same across the board.

From what I read the commit is True by default - because when you save a form usually you want to immediately save it to the data-base itself too (the save method returns an object of the model the form is attached to anyway). When you call with `commit=False` Django does not try to save the apartment (in this case) to the data-base and only returns an apartment object. this is good in this case because the `ApartmentCreationForm` does not have an `owner` field, which means that calling the save method with `commit=True` will probably break and at least have undefined behavior.
I designed the form this way because both the apartment and seeker users have the `User` fields, so I thought that re-writing them in both forms is a waste and decided to write a `UserCreationForm` which holds all the fields of the `User` and is meant to be called with the `SeekerCreationForm` or the `ApartmentCreationForm`

**Comment by simzacks** [comment]
You really want the functionality to be unified.
.save() on all objects should either do a real save or a not-real save.
Currently, if you call `ApartmentCreationForm.save()` it will not save it to the database, but if you call `ApartmentDetailsUpdateForm.save()` it will save it to the database.
So when you're looking at the code and you see a form being saved it is difficult to know if it is saving to the database or not.
It is also confusing when writing new code, you will have to go to each object and check whether this is an object with the default of commit = true or false.

**Comment by Micha546** [comment]
> You really want the functionality to be unified.
> .save() on all objects should either do a real save or a not-real save.
> Currently, if you call `ApartmentCreationForm.save()` it will not save it to the database, but if you call `ApartmentDetailsUpdateForm.save()` it will save it to the database.
> So when you're looking at the code and you see a form being saved it is difficult to know if it is saving to the database or not.
> It is also confusing when writing new code, you will have to go to each object and check whether this is an object with the default of commit = true or false.

Ok, I will change the code to call the save function with the commit explicitly and push it as a new commit

**Comment by Micha546** [comment]
> > You really want the functionality to be unified.
> > .save() on all objects should either do a real save or a not-real save.
> > Currently, if you call `ApartmentCreationForm.save()` it will not save it to the database, but if you call `ApartmentDetailsUpdateForm.save()` it will save it to the database.
> > So when you're looking at the code and you see a form being saved it is difficult to know if it is saving to the database or not.
> > It is also confusing when writing new code, you will have to go to each object and check whether this is an object with the default of commit = true or false.
> 
> Ok, I will change the code to call the save function with the commit explicitly and push it as a new commit

@simzacks 
Nevermind, I see that the code that calls the save method is already explicit:
image
Do you think that changing the default value of the commit to be true will make more sense?

**Review by OrAsaf — APPROVED** [review]

**Pull request merged**
