### PR TITLE
Removing all migration files

### LINKED ISSUE #88: Remove all migration files
So we can makemigration to new files that won't conflict

### PR DESCRIPTION
**Pull request by Micha546**
We decided to restart the migration files,
this is the first step.

**note:** pytest won't work in this PR please ignore

Fix #88

### CODE REVIEW

**Review by DanielMy777 — COMMENTED** [review]
Looks good, are you adding the new ones on another PR?

**Comment by Micha546** [comment]
> Looks good, are you adding the new ones on another PR?

Yes, added the new PR already

**Review by OrAsaf — APPROVED** [review]
This was discussed in the Slack channel so I approve.
I looked at the next PRs as well and I assume they were all tested and the test data is working after merging everything (this is important so you can show everything properly in the demo).

**Comment by Micha546** [comment]
> This was discussed in the Slack channel so I approve.
> I looked at the next PRs as well and I assume they were all tested and the test data is working after merging everything (this is important so you can show everything properly in the demo).

Yes it works, I can see the data in /admin and in the shell,
also pytest passes all tests

**Review by nadavsu — APPROVED** [review]

**Review by tamirho — APPROVED** [review]
LGTM

**Review by simzacks — APPROVED** [review]

**Pull request merged**
