### PR TITLE
Redesigning all the tests

### LINKED ISSUE #144: Redesign tests
We need to redesign the tests so they will use the same fixtures

### PR DESCRIPTION
**Pull request by Micha546**
# Description
Moved all the fixtures to a new file - conftest.py
Changed some tests to use get_user_model instead of make_user
Deleted some fixtures that were defined multiple times
Deleted imports that were no longer in use

## Manual Tests
Ran pytest alot of times

### Issues close by this PR
Fix #144

### CODE REVIEW

**Review by DanielMy777 — COMMENTED** [review]
Nice work!
I assume this all works as you 'ran pytest a lot of times' 😆

**Review by simzacks — COMMENTED** [review]
There seems to be overlap with #136  I'll review this after that has been merged and this has been rebased.

**Comment by Micha546** [comment]
> There seems to be overlap with #136 I'll review this after that has been merged and this has been rebased.

This PR is supposed to merge first

**Comment by Omeramsc** [comment]
It looks OK, but hard to review it thoroughly. 
Can you elaborate on which fixtures were removed due to duplication, or why the tests changed to use get_user_model?

**Comment by Micha546** [comment]
> It looks OK, but hard to review it thoroughly.
> Can you elaborate on which fixtures were removed due to duplication, or why the tests changed to use get_user_model?

@simzacks reviewed alot of the changes in #136.
I used the `get_user_model().objects.create_user` instead of the `make_user` fixture because they do the same thing, so I thought that it's better to use the function that already exists.
I removed couple of `new_city` and `new_user` fixtures and used one fixture instead.

**Comment by Micha546** [comment]
@simzacks I've changed a few things that you asked for, check it out.
the other things I have commented on the change request you wrote in #136

**Review by tamirho — APPROVED** [review]
LGTM

**Comment by AmitAharoni** [comment]
LGTM :)

**Review by OrAsaf — APPROVED** [review]

**Review by simzacks — APPROVED** [review]

**Pull request merged**
