### PR TITLE
Alter navbar `bgcolor`

### LINKED ISSUE #187: Alter navbar `bgcolor`
- Alter navbar `bgcolor` to be the same color as the logo

### PR DESCRIPTION
**Pull request by tamirho**
# Description
- Alter the navbar `bgcolor` to be the same color as the logo.

## Screenshots
Before:
Capture2

After:
Capture

### Issues closed by this PR
Fix: #187

### CODE REVIEW

**Comment by AmitAharoni** [comment]
Well done

**Review by AmitAharoni — APPROVED** [review]

**Comment by nadavsu** [comment]
The problem isn't with the navbar, but with the logo background.
The logo background is a gradient, we need to change it to a single solid color.
But what you did looks good too.

**Review by DanielMy777 — APPROVED** [review]
LGTM

**Review by Micha546 — APPROVED** [review]
LGTM

**Pull request merged**
