### PR TITLE
Adding a migration file for Apartment

### LINKED ISSUE #62: Add a migration file for the name changes of the Apartment fields

### PR DESCRIPTION
**Pull request by Micha546**
There was no migration file for the name changes in
Apartment, which caused the test data to not migrate
properly.

**note:** also changed names in the test data file to be the same
               as the new names of the fields in Apartment.
fix #62

### CODE REVIEW

**Comment by nadavsu** [comment]
Nice!

**Review by DanielMy777 — COMMENTED** [review]
Looking great!

**Comment by tamirho** [comment]
LGTM

**Review by AmitAharoni — COMMENTED** [review]
Well done Micha

**Review by simzacks — APPROVED** [review]
lgtm

**Review by Omeramsc — APPROVED** [review]
LGTM

**Pull request merged**
