### PR TITLE
Adding hobby field

### LINKED ISSUE #46: Create user hobbies field
User hobbies will be a many to many field, as many users can choose a number of hobbies.
The hobbies will be used to give a seeker and an owner a matching score in the future.

### PR DESCRIPTION
**Pull request by nadavsu**
Hobby is a many to many field inside the user class.
Every user can choose a number of hobbies when signing up.
The hobbies are used to match between an apartment owner and seeker.

Also updated .gitignore to include macOS directory config files.
Fixes #46

### CODE REVIEW

**Comment by nadavsu** [comment]
I'm not sure whether we should push the migration files, as we will definitely have a conflict when we'll try to merge our PRs.
Maybe we should exclude them from our PRs and instead run the migrate command after we pull from upstream?

**Review by simzacks — APPROVED** [review]

**Comment by simzacks** [comment]
The only migrations you really need to share are the ones you do manually to add data to the system. This is done for either testing, or to populate tables with data that the application expects to be there.
All the other ones can probably be added to the vagrantfile so that it automatically does makemigrations and migrate when the system comes up.

**Comment by AmitAharoni** [comment]
LGTM

**Comment by Micha546** [comment]
@simzacks should we add the migration folders to the .gitignore and add makemigrations to the bootstrap.sh?

**Review by Micha546 — COMMENTED** [review]
Other than the migration files which will maybe create a conflict with @tamirho s PR, everything looks 🔥

**Comment by simzacks** [comment]
I think adding the migration files to the .gitignore would be a great idea. With one caveat. There are some migration files that are manually created. For example, when you add test data to the system, or preload data (such as lookup information) in.
So those would have to be included in any case.

**Comment by DanielMy777** [comment]
@nadavsu Please add Omer and Or as reviewers.
Good job with the hobbies model! watch for the migration files as @Micha546 said :)

**Comment by OrAsaf** [comment]
LGTM, note that user migration files are in the repo (and the PR).

**Comment by nadavsu** [comment]
> LGTM, note that user migration files are in the repo (and the PR).

Yep. Added an issue and will soon submit a new PR closing it.

**Pull request merged**
